server:
  port: 8094

spring:
  application:
    name: goods-page
  thymeleaf:
    cache: false #关闭缓存
  rabbitmq:
    host: 192.168.81.6
    username: wlkg
    password: 123456
    virtual-host: /wlkg
wlkg:
  thymeleaf:
    destPath: E:/window_software/nginx-1.8.0/nginx-1.8.0/html/bak_html



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${server.port}
