server:
  port: 8091
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3307/wlkg
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

  rabbitmq:
    host: 192.168.81.6
    username: wlkg
    password: 123456
    virtual-host: /wlkg
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: wlkg.item.exchange
    publisher-confirms: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
